version: '3'

services:
    app:
        build: .
        container_name: course-django-app
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/home/django/app
        ports:
            - "8000:8000"
        depends_on: 
            - db
    
    db:
        image: postgres
        container_name: course-django-db
        tty: true
        environment: 
            - POSTGRES_DB=course_django
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
        volumes: 
            - course-django-pgdata:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: course-django-pgadmin
        tty: true
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@user.com
            - PGADMIN_DEFAULT_PASSWORD=123456
        ports:
            - "9000:80"

volumes: 
    course-django-pgdata:
        external: true
